INSERT INTO barcodes (barcode, name, specs) VALUES
(1, 'Μπαταρία Lipo Gens Ace','1000mAh 7.4V'),
(1, 'Μπαταρία Lipo Zon Cell','400mAh 3.7V 1.48 Wh'),
(1, 'Μπαταρία Lipo Zon Cell','600mAh 3.7V 2.2Wh'),
(1, 'Μπαταρία Lipo Zon Cell','1200mAh 3.7V 4.44 Wh'),
(1, 'Μπαταρία Lipo Zon Cell','2500mAh 3.7V 9.25Wh'),
(1, 'Cellevia Batteries','800mAh 3.7V 2.96Wh'),
(1, 'Cellevia Batteries','550mAh 3.7V 2.035Wh'),
(1, 'Lipo Battery Charger','Type C'),
(1, 'Apacer microSDHC Card','16GB, Up to 85MB/s'),
(1, 'Apacer microSDHC Card','32GB, Up to 85MB/s'),
(1, 'Καλώδιο HDMI','HDMI to Micro HDMI'),
(1, 'Τροφοδοτικό ULLPOWER','5V'),
(1, 'Tower Pro Micro Servo 9g SG90','Με μεταλλικά γρανάζια'),
(1, 'Tower Pro Micro Servo 9g SG90','Με πλαστικά γρανάζια'),
(1, 'Πλακέτα Προστασίας BMS/PCB','40A 12.6V - 13.6V'),
(1, 'Eachine TX1200 FPV Transmitter','25/200/600/1000mW 5.8GHz'),
(1, 'Raspberry Pi Camera Module','5MP Day & Night Vision'),
(1, 'PCA9685 PWM Servo Motor Driver','16 Channel 12 Bit I2C Module'),
(1, 'HW-237 NRFF24L01+PA+LNA','2.4GHz Wireless Module with Antenna'),
(1, 'ROHS Step Motor 28BYJ-48','5V DC'),
(1, 'ULN 2003 Stepper Motor Driver','0 - 5V Digital Output (Requires 6V to 30V Supply)'),
(1, 'USB Step Down DC-DC Converter','6-24V to 5V'),
(1, 'Triple Feed Antenna Directional Circularly Polarized Antenna for FPV RC Drone','5.8GHz'),
(1, 'Mt 2204 Brushless Motor','2300KV'),
(1, 'Διακόπτης Toggle On-Off Μονοπολικός','15A/250V'),
(1, 'Κάμερα CMOS OV7670','640x480'),
(1, 'Αισθητήρας Άνθρακας & Μεθανίου MQ4','Ιδανικό για τα εξής αέρια: H2, LPG, CH4, CO, Alcohol'),
(1, 'Raspberry Pi 5 Official USB-C Pd Power Supply','27W'),
(1, 'Καλώδιο Τροφοδοσίας','Output 8.4V'),
(1, 'Power Brick (Για Breadboard)',', Output: 5V'),
(1, 'Speaker Waterproof','2W 8Ohm - 50mm'),
(1, 'Power Supply','12V 3A'),
(1, 'Samsung INR 18650 Επαναφορτιζόμενες','3500mAh 3.7V'),
(1, 'Step Down Power Supply Buck Converter','DC-DC 24V/12V To 5V 5A'),
(1, 'Adafruit Mono Class D Audio Amplifier - PAM8302','2.5W'),
(1, 'Visaton K 50 Audio Speaker J21','8Ω');

INSERT INTO barcodes (barcode, name) VALUES
(1, 'Σερβοκινητήρας MG996R'),
(1, 'Σερβοκινητήρας Feetec Servo FS5106M'),
(1, 'Σερβοκινητήρας Feetec Servo FB5118M'),
(1, 'Σερβοκινητήρας MG90S'),
(1, 'Μετατροπέας DC-DC Step-Up 5-28V 2A'),
(1, 'STM32 Small Development Board'),
(1, 'Raspberry Pi Zero'),
(1, 'Motor Control Shield'),
(1, 'Arduino Nano RP2040'),
(1, 'Arduino Uno'),
(1, 'Adafruit Log-scale Analog Light Sensor'),
(1, 'Mechanical Endstop Limit Switch With Cable for 3D Printer (Arduino Compatible),'),
(1, 'L293 IC Motor Driver Chip'),
(1, 'ESP8266 WiFi Wireless Transceiver Module'),
(1, 'Hall Effect Magnetic Senson Module DC 5V για Arduino'),
(1, 'Pro Mini ATMega328, 3.3V 8MHz (Συμβατό με Arduino),'),
(1, 'HC05 Bluetooth Module for Arduino'),
(1, 'Waveshare Αισθητήρας Θερμοκρασία/Υγρασίας BME280'),
(1, 'Module Micro SD Card'),
(1, 'Stepper StepStick DRV8825 for DIY Printer'),
(1, 'Μπλέ καλώδιο τροφοδοσίας για Arduino'),
(1, 'Eachine ROTG02 Πολυμορφικός δέκτης ήχου FPV για Android Smartphone, 5.8GHz 150CH'),
(1, 'Arduino Mega'),
(1, 'Raspberry Pi 5'),
(1, 'Arduino Nano IoT'),
(1, 'Element14 PiFace Digital Interface Board Raspberry Pi 2 Relay 8'),
(1, 'Αισθητήρας Θερμοκρασίας & Υγρασίας DHT11'),
(1, 'Αισθητήρας Μονοξειδίου του Άνθρακα MQ7'),
(1, 'Waveshare Infrared Proximity Sensor'),
(1, '8-Channel Bi-Directional Logic Level Shifter'),
(1, 'Photoresistor LDR Breakout Board'),
(1, 'Voice Sound Module KY-038'),
(1, 'DFRobot IO Expansion Hat for Pi Zero'),
(1, 'BMS Lithium Battery Charger Module'),
(1, 'MicroSD Adapter'),
(1, '18650X3 Battery Case'),
(1, 'Pi Hat'),
(1, 'L298N Motor Driver Module'),
(1, 'Triple Axis Gyroscope Accelerometer - MPU6050'),
(1, 'DC Wheel Motor'),
(1, 'LED 5050 SMD Module RGB'),
(1, 'Photoresistor Module'),
(1, 'Οπτικός Χιλιομετρητής'),
(1, 'L293D Motor Drive Shield');